apiVersion: v1
kind: Secret
metadata:
  name: db-passwords
type: Opaque # Означает, что это произвольные данные
stringData:
  DB_PASSWORD: "SuperSecretPassword123" # Kubernetes сам закодирует это в base64
