apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lab-incident-12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        # Загружаем простые настройки из ConfigMap
        envFrom:
        - configMapRef:
            name: app-config
        # Загружаем пароль из Secret
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
