apiVersion: v1
kind: Service
metadata:
  name: postgres # Это будет DNS-имя базы внутри кластера
  namespace: lab-incident-12
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432      # Порт, на котором слушает сервис
      targetPort: 5432 # Порт внутри контейнера
  type: ClusterIP      # База будет видна только внутри кластера
